# permissions for end users to edit redisrafts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisraft-editor-role
rules:
- apiGroups:
  - db.tsurai.dev
  resources:
  - redisrafts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.tsurai.dev
  resources:
  - redisrafts/status
  verbs:
  - get
